version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80  # Change this to a different host port
    volumes:
      - ./src/pages:/var/www/html/
    restart: always
    networks:
      - lan
      
  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "6066:3306"  # Change this to a different host port
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lan

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'  # Change this to a different host port
    environment:
      PMA_HOST: db
    networks:
      - lan 

volumes:
  dbdata:

networks:
  lan:
